version: '3'
services:
  userver-postgres:
    container_name: userver-postgres
    image: postgres:12-alpine
    command: postgres -c config_file=/etc/postgresql/config/postgresql.conf
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/config:/etc/postgresql/config
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  userver-redis:
    image: redis
    container_name: userver-redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  userver-adminer:
    image: adminer
    container_name: userver-adminer
    env_file:
      - ./adminer/.env
    depends_on:
      - userver-postgres
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 20s
      retries: 3

  userver-databackup:
    image: ferdn4ndo/s3-postgres-backup:latest
    container_name: userver-databackup
    env_file:
      - ./backup/.env
    depends_on:
      - userver-postgres

networks:
  default:
    external: true
    name: nginx-proxy

volumes:
  dbdata:
