name: E2E Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs: # Docs: <https://git.io/JvxXE>
  run-ats:
    name: Run the End-to-End (E2E) Automated Tests (AT)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from uServer-Web
        uses: actions/checkout@v7
        with:
          repository: ferdn4ndo/userver-web
          path: userver-web

      - name: Build and deploy uServer Web services
        uses: ./userver-web/.github/actions/deploy_local
        with:
          monitor-virtual-host: "monitor.userver.lan"
          whoami-virtual-host: "whoami.userver.lan"
          root-work-dir: "./userver-web"

      - name: Check out code
        uses: actions/checkout@v7

      - name: Build and deploy uServer DataMgr services
        uses: ./.github/actions/deploy_local
        with:
          adminer-virtual-host: "adminer.userver.lan"
          aws-s3-access-key-id: "${{ secrets.S3_ACCESS_KEY_ID }}"
          aws-s3-secret-access-key: "${{ secrets.S3_SECRET_ACCESS_KEY }}"
          aws-s3-bucket: "${{ secrets.S3_BUCKET }}"
          aws-s3-region: "${{ secrets.S3_REGION }}"
          postgres-password: "${{ secrets.POSTGRES_PASSWORD }}"
          backup-encryption-password: "${{ secrets.BACKUP_ENCRYPTION_PASSWORD }}"

      - name: Wait 10 seconds for startup
        run: sleep 10s
        shell: bash

      - name: Run the End-to-End (E2E) tests
        run: ./run_e2e_tests.sh
        shell: bash
